// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api.proto

package apiv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchEvent_Type int32

const (
	WatchEvent_UNKNOWN  WatchEvent_Type = 0
	WatchEvent_ADDED    WatchEvent_Type = 1 // first observed (or seen for the first time this stream)
	WatchEvent_MODIFIED WatchEvent_Type = 2 // observed state or drift changed since last emit
	WatchEvent_DELETED  WatchEvent_Type = 3 // gone from the controller's view (resource.name still set)
)

// Enum value maps for WatchEvent_Type.
var (
	WatchEvent_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "ADDED",
		2: "MODIFIED",
		3: "DELETED",
	}
	WatchEvent_Type_value = map[string]int32{
		"UNKNOWN":  0,
		"ADDED":    1,
		"MODIFIED": 2,
		"DELETED":  3,
	}
)

func (x WatchEvent_Type) Enum() *WatchEvent_Type {
	p := new(WatchEvent_Type)
	*p = x
	return p
}

func (x WatchEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (WatchEvent_Type) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x WatchEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEvent_Type.Descriptor instead.
func (WatchEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14, 0}
}

type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional caller-supplied string echoed back. Useful for correlating
	// requests/responses in scripted checks.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The caller's `message`, echoed verbatim.
	Echo string `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	// Semver-ish version string of the controller binary.
	ServerVersion string `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

func (x *PingResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

// Resource is the k8s-style envelope for any resource kind. spec/status are
// generic structured values to keep the proto kind-agnostic.
type Resource struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"` // e.g. "proxmox.openctl.io/v1"
	Kind       string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                               // e.g. "VirtualMachine"
	Metadata   *Metadata              `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec       *structpb.Struct       `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status     *structpb.Struct       `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Phase 5: drift surfaces "the resource set/spec differs from the manifest".
	// Populated only on Get/List responses, after the controller compares the
	// observed state against the persisted desired state. Empty entries means
	// either the resource matches its manifest or no manifest is on file
	// (e.g. resource was created out-of-band).
	Drift         []*DriftEntry `protobuf:"bytes,6,rep,name=drift,proto3" json:"drift,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetSpec() *structpb.Struct {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetStatus() *structpb.Struct {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Resource) GetDrift() []*DriftEntry {
	if x != nil {
		return x.Drift
	}
	return nil
}

// DriftEntry describes a single field where the observed state differs from
// the desired state. path is a dot-separated walk into the spec
// (e.g. "spec.cpus" or "spec.nodes.workers[0].count"); desired and observed
// are the values rendered as strings for human display.
type DriftEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Desired       string                 `protobuf:"bytes,2,opt,name=desired,proto3" json:"desired,omitempty"`
	Observed      string                 `protobuf:"bytes,3,opt,name=observed,proto3" json:"observed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriftEntry) Reset() {
	*x = DriftEntry{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriftEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriftEntry) ProtoMessage() {}

func (x *DriftEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriftEntry.ProtoReflect.Descriptor instead.
func (*DriftEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *DriftEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DriftEntry) GetDesired() string {
	if x != nil {
		return x.Desired
	}
	return ""
}

func (x *DriftEntry) GetObserved() string {
	if x != nil {
		return x.Observed
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type ApplyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Resource *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Phase 5 destructive guardrails. allow_destructive permits removing
	// declared children (e.g. scaling a Cluster down). i_know_this_breaks_the_cluster
	// overrides the catastrophic-op block (single-CP recreate, quorum loss,
	// last-worker removal). Both default false; the CLI exposes them as
	// --allow-destructive and --i-know-this-breaks-the-cluster.
	AllowDestructive          bool `protobuf:"varint,2,opt,name=allow_destructive,json=allowDestructive,proto3" json:"allow_destructive,omitempty"`
	IKnowThisBreaksTheCluster bool `protobuf:"varint,3,opt,name=i_know_this_breaks_the_cluster,json=iKnowThisBreaksTheCluster,proto3" json:"i_know_this_breaks_the_cluster,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *ApplyRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ApplyRequest) GetAllowDestructive() bool {
	if x != nil {
		return x.AllowDestructive
	}
	return false
}

func (x *ApplyRequest) GetIKnowThisBreaksTheCluster() bool {
	if x != nil {
		return x.IKnowThisBreaksTheCluster
	}
	return false
}

type ApplyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// operation_id identifies the async operation that will (eventually)
	// converge the resource. Use OperationService.GetOperation to poll for
	// completion, or pass --no-wait to the CLI to fire-and-forget.
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Human-friendly message describing what was submitted.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ApplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ListRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *DeleteRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// operation_id identifies the async operation; poll via OperationService.
	OperationId   string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// WatchRequest configures a resource Watch stream. api_version + kind are
// required (you must scope to a kind because there's no cross-kind list
// in the controller); name optional to narrow to one resource.
type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *WatchRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *WatchRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WatchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// WatchEvent describes a single resource change. The first batch after
// subscribe carries one ADDED event per existing resource so the client
// gets a complete snapshot before live deltas start.
type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WatchEvent_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=openctl.v1.WatchEvent_Type" json:"type,omitempty"`
	Resource      *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *WatchEvent) GetType() WatchEvent_Type {
	if x != nil {
		return x.Type
	}
	return WatchEvent_UNKNOWN
}

func (x *WatchEvent) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type Operation struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId     string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // empty for top-level ops; populated for child rows
	Type         string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                         // "apply" | "delete" | "step"
	ApiVersion   string                 `protobuf:"bytes,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind         string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	ResourceName string                 `protobuf:"bytes,6,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Status       string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                               // pending | running | succeeded | failed | interrupted
	Error        string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`                                 // populated on failed/interrupted
	SubmittedAt  string                 `protobuf:"bytes,9,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`  // RFC3339
	StartedAt    string                 `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`       // empty until claimed
	CompletedAt  string                 `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // empty until terminal
	Result       *Resource              `protobuf:"bytes,12,opt,name=result,proto3" json:"result,omitempty"`                              // populated on succeeded apply
	// Phase 4.5: human-readable label for sub-step ops (e.g. "install-k3s").
	// Empty for top-level apply/delete unless explicitly set.
	Label string `protobuf:"bytes,13,opt,name=label,proto3" json:"label,omitempty"`
	// Phase 4.5: child operations for composite resources. Populated only when
	// GetOperation is called with include_children=true (omitted from List
	// responses to keep them cheap).
	Children      []*Operation `protobuf:"bytes,14,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Operation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Operation) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Operation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Operation) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *Operation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Operation) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Operation) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

func (x *Operation) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Operation) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *Operation) GetResult() *Resource {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Operation) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Operation) GetChildren() []*Operation {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Phase 4.5: include child operations in the response. Children are
	// ordered oldest first. List responses never include children.
	IncludeChildren bool `protobuf:"varint,2,opt,name=include_children,json=includeChildren,proto3" json:"include_children,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *GetOperationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOperationRequest) GetIncludeChildren() bool {
	if x != nil {
		return x.IncludeChildren
	}
	return false
}

type ListOperationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All filters optional — empty means match-all.
	Status       string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ApiVersion   string `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind         string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	ResourceName string `protobuf:"bytes,4,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Cap on results returned, newest-first. 0 = no cap.
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsRequest) Reset() {
	*x = ListOperationsRequest{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsRequest) ProtoMessage() {}

func (x *ListOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *ListOperationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListOperationsRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ListOperationsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListOperationsRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ListOperationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *ListOperationsResponse) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable display name (e.g. browser/device label) shown in
	// session listings. Optional.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// TTL in seconds for the new session. 0 = server default
	// (auth.DefaultSessionTTL = 7 days).
	TtlSeconds    int64 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *LoginRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LoginRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw session token. Pass as `Bearer <token>` in subsequent requests
	// (or wait for U1.3 to wrap as an HttpOnly cookie).
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpiresAt     string `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

// WhoAmIResponse returns identifying info about the auth credential used
// on the call. For root-bearer-token callers user_id is empty; for
// session-token callers it carries the session's user_id (always
// "default" in single-user mode).
type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // empty if authenticated via root bearer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

func (x *WhoAmIResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WhoAmIResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasRequest) Reset() {
	*x = ListSchemasRequest{}
	mi := &file_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasRequest) ProtoMessage() {}

func (x *ListSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListSchemasRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{25}
}

type ListSchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*SchemaInfo          `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{26}
}

func (x *ListSchemasResponse) GetSchemas() []*SchemaInfo {
	if x != nil {
		return x.Schemas
	}
	return nil
}

// SchemaInfo describes one embedded CUE schema. file_name is the relative
// path under internal/schema/schemas/ (e.g. "proxmox/vm.cue") so the
// client can compose links back to source if it wants to.
type SchemaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"` // e.g. "proxmox.openctl.io/v1"
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                               // e.g. "VirtualMachine"
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`                       // e.g. "proxmox"
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaInfo) Reset() {
	*x = SchemaInfo{}
	mi := &file_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaInfo) ProtoMessage() {}

func (x *SchemaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaInfo.ProtoReflect.Descriptor instead.
func (*SchemaInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{27}
}

func (x *SchemaInfo) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *SchemaInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SchemaInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SchemaInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{28}
}

func (x *GetSchemaRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetSchemaRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type GetSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Info  *SchemaInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// CUE source text. Multi-file packages join all files in deterministic
	// order so a single string is sufficient for editor consumption.
	CueSource     string `protobuf:"bytes,2,opt,name=cue_source,json=cueSource,proto3" json:"cue_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{29}
}

func (x *GetSchemaResponse) GetInfo() *SchemaInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetSchemaResponse) GetCueSource() string {
	if x != nil {
		return x.CueSource
	}
	return ""
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{30}
}

func (x *ValidateRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty errors[] = valid. Populated = validation failed; each entry is
	// one human-readable diagnostic. No structured location info yet — CUE
	// doesn't surface it cleanly through Validate; future enhancement.
	Errors        []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{31}
}

func (x *ValidateResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type WatchOperationsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // narrow to one op id (terminate when terminal)
	ApiVersion      string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind            string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	ResourceName    string                 `protobuf:"bytes,4,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	IncludeChildren bool                   `protobuf:"varint,5,opt,name=include_children,json=includeChildren,proto3" json:"include_children,omitempty"` // populate children on each emitted op
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchOperationsRequest) Reset() {
	*x = WatchOperationsRequest{}
	mi := &file_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchOperationsRequest) ProtoMessage() {}

func (x *WatchOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchOperationsRequest.ProtoReflect.Descriptor instead.
func (*WatchOperationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{32}
}

func (x *WatchOperationsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WatchOperationsRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *WatchOperationsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WatchOperationsRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *WatchOperationsRequest) GetIncludeChildren() bool {
	if x != nil {
		return x.IncludeChildren
	}
	return false
}

// OperationEvent carries an op state transition. The full op is included
// (not a delta); clients render it directly. The first batch after
// subscribe emits all ops matching the filter so the client gets a
// snapshot. terminal=true signals the op reached a terminal status; for
// id-scoped subscribes that's the cue to close the stream.
type OperationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Terminal      bool                   `protobuf:"varint,2,opt,name=terminal,proto3" json:"terminal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationEvent) Reset() {
	*x = OperationEvent{}
	mi := &file_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationEvent) ProtoMessage() {}

func (x *OperationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationEvent.ProtoReflect.Descriptor instead.
func (*OperationEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{33}
}

func (x *OperationEvent) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *OperationEvent) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\n" +
	"openctl.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"I\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04echo\x18\x01 \x01(\tR\x04echo\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\"\xfd\x01\n" +
	"\bResource\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.openctl.v1.MetadataR\bmetadata\x12+\n" +
	"\x04spec\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04spec\x12/\n" +
	"\x06status\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06status\x12,\n" +
	"\x05drift\x18\x06 \x03(\v2\x16.openctl.v1.DriftEntryR\x05drift\"V\n" +
	"\n" +
	"DriftEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\adesired\x18\x02 \x01(\tR\adesired\x12\x1a\n" +
	"\bobserved\x18\x03 \x01(\tR\bobserved\"\x9c\x02\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\x06labels\x18\x02 \x03(\v2 .openctl.v1.Metadata.LabelsEntryR\x06labels\x12G\n" +
	"\vannotations\x18\x03 \x03(\v2%.openctl.v1.Metadata.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\fApplyRequest\x120\n" +
	"\bresource\x18\x01 \x01(\v2\x14.openctl.v1.ResourceR\bresource\x12+\n" +
	"\x11allow_destructive\x18\x02 \x01(\bR\x10allowDestructive\x12A\n" +
	"\x1ei_know_this_breaks_the_cluster\x18\x03 \x01(\bR\x19iKnowThisBreaksTheCluster\"L\n" +
	"\rApplyResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\n" +
	"GetRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"?\n" +
	"\vGetResponse\x120\n" +
	"\bresource\x18\x01 \x01(\v2\x14.openctl.v1.ResourceR\bresource\"B\n" +
	"\vListRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"B\n" +
	"\fListResponse\x122\n" +
	"\tresources\x18\x01 \x03(\v2\x14.openctl.v1.ResourceR\tresources\"X\n" +
	"\rDeleteRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"M\n" +
	"\x0eDeleteResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\fWatchRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xaa\x01\n" +
	"\n" +
	"WatchEvent\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.openctl.v1.WatchEvent.TypeR\x04type\x120\n" +
	"\bresource\x18\x02 \x01(\v2\x14.openctl.v1.ResourceR\bresource\"9\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05ADDED\x10\x01\x12\f\n" +
	"\bMODIFIED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03\"\xb0\x03\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12#\n" +
	"\rresource_name\x18\x06 \x01(\tR\fresourceName\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12!\n" +
	"\fsubmitted_at\x18\t \x01(\tR\vsubmittedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\v \x01(\tR\vcompletedAt\x12,\n" +
	"\x06result\x18\f \x01(\v2\x14.openctl.v1.ResourceR\x06result\x12\x14\n" +
	"\x05label\x18\r \x01(\tR\x05label\x121\n" +
	"\bchildren\x18\x0e \x03(\v2\x15.openctl.v1.OperationR\bchildren\"P\n" +
	"\x13GetOperationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10include_children\x18\x02 \x01(\bR\x0fincludeChildren\"\x9f\x01\n" +
	"\x15ListOperationsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12#\n" +
	"\rresource_name\x18\x04 \x01(\tR\fresourceName\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"O\n" +
	"\x16ListOperationsResponse\x125\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x15.openctl.v1.OperationR\n" +
	"operations\"R\n" +
	"\fLoginRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"c\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"\x0f\n" +
	"\rWhoAmIRequest\"H\n" +
	"\x0eWhoAmIResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x14\n" +
	"\x12ListSchemasRequest\"G\n" +
	"\x13ListSchemasResponse\x120\n" +
	"\aschemas\x18\x01 \x03(\v2\x16.openctl.v1.SchemaInfoR\aschemas\"z\n" +
	"\n" +
	"SchemaInfo\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\"G\n" +
	"\x10GetSchemaRequest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"^\n" +
	"\x11GetSchemaResponse\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.openctl.v1.SchemaInfoR\x04info\x12\x1d\n" +
	"\n" +
	"cue_source\x18\x02 \x01(\tR\tcueSource\"C\n" +
	"\x0fValidateRequest\x120\n" +
	"\bresource\x18\x01 \x01(\v2\x14.openctl.v1.ResourceR\bresource\"*\n" +
	"\x10ValidateResponse\x12\x16\n" +
	"\x06errors\x18\x01 \x03(\tR\x06errors\"\xad\x01\n" +
	"\x16WatchOperationsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12#\n" +
	"\rresource_name\x18\x04 \x01(\tR\fresourceName\x12)\n" +
	"\x10include_children\x18\x05 \x01(\bR\x0fincludeChildren\"a\n" +
	"\x0eOperationEvent\x123\n" +
	"\toperation\x18\x01 \x01(\v2\x15.openctl.v1.OperationR\toperation\x12\x1a\n" +
	"\bterminal\x18\x02 \x01(\bR\bterminal2Z\n" +
	"\vPingService\x12K\n" +
	"\x04Ping\x12\x17.openctl.v1.PingRequest\x1a\x18.openctl.v1.PingResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/ping2\xde\x03\n" +
	"\x0fResourceService\x12\\\n" +
	"\x05Apply\x12\x18.openctl.v1.ApplyRequest\x1a\x19.openctl.v1.ApplyResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/resources:apply\x12T\n" +
	"\x03Get\x12\x16.openctl.v1.GetRequest\x1a\x17.openctl.v1.GetResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/resources:get\x12X\n" +
	"\x04List\x12\x17.openctl.v1.ListRequest\x1a\x18.openctl.v1.ListResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/resources:list\x12`\n" +
	"\x06Delete\x12\x19.openctl.v1.DeleteRequest\x1a\x1a.openctl.v1.DeleteResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/resources:delete\x12[\n" +
	"\x05Watch\x12\x18.openctl.v1.WatchRequest\x1a\x16.openctl.v1.WatchEvent\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/resources:watch0\x012\xe6\x02\n" +
	"\x10OperationService\x12c\n" +
	"\fGetOperation\x12\x1f.openctl.v1.GetOperationRequest\x1a\x15.openctl.v1.Operation\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/operations/{id}\x12w\n" +
	"\x0eListOperations\x12!.openctl.v1.ListOperationsRequest\x1a\".openctl.v1.ListOperationsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/operations:list\x12t\n" +
	"\x0fWatchOperations\x12\".openctl.v1.WatchOperationsRequest\x1a\x1a.openctl.v1.OperationEvent\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/operations:watch0\x012\xa9\x02\n" +
	"\x0eSessionService\x12Z\n" +
	"\x05Login\x12\x18.openctl.v1.LoginRequest\x1a\x19.openctl.v1.LoginResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/session/login\x12^\n" +
	"\x06Logout\x12\x19.openctl.v1.LogoutRequest\x1a\x1a.openctl.v1.LogoutResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/session/logout\x12[\n" +
	"\x06WhoAmI\x12\x19.openctl.v1.WhoAmIRequest\x1a\x1a.openctl.v1.WhoAmIResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/session/whoami2\xc2\x02\n" +
	"\rSchemaService\x12c\n" +
	"\vListSchemas\x12\x1e.openctl.v1.ListSchemasRequest\x1a\x1f.openctl.v1.ListSchemasResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/schemas\x12d\n" +
	"\tGetSchema\x12\x1c.openctl.v1.GetSchemaRequest\x1a\x1d.openctl.v1.GetSchemaResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/schemas:get\x12f\n" +
	"\bValidate\x12\x1b.openctl.v1.ValidateRequest\x1a\x1c.openctl.v1.ValidateResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/schemas:validateB-Z+github.com/openctl/openctl/pkg/api/v1;apiv1b\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_api_proto_goTypes = []any{
	(WatchEvent_Type)(0),           // 0: openctl.v1.WatchEvent.Type
	(*PingRequest)(nil),            // 1: openctl.v1.PingRequest
	(*PingResponse)(nil),           // 2: openctl.v1.PingResponse
	(*Resource)(nil),               // 3: openctl.v1.Resource
	(*DriftEntry)(nil),             // 4: openctl.v1.DriftEntry
	(*Metadata)(nil),               // 5: openctl.v1.Metadata
	(*ApplyRequest)(nil),           // 6: openctl.v1.ApplyRequest
	(*ApplyResponse)(nil),          // 7: openctl.v1.ApplyResponse
	(*GetRequest)(nil),             // 8: openctl.v1.GetRequest
	(*GetResponse)(nil),            // 9: openctl.v1.GetResponse
	(*ListRequest)(nil),            // 10: openctl.v1.ListRequest
	(*ListResponse)(nil),           // 11: openctl.v1.ListResponse
	(*DeleteRequest)(nil),          // 12: openctl.v1.DeleteRequest
	(*DeleteResponse)(nil),         // 13: openctl.v1.DeleteResponse
	(*WatchRequest)(nil),           // 14: openctl.v1.WatchRequest
	(*WatchEvent)(nil),             // 15: openctl.v1.WatchEvent
	(*Operation)(nil),              // 16: openctl.v1.Operation
	(*GetOperationRequest)(nil),    // 17: openctl.v1.GetOperationRequest
	(*ListOperationsRequest)(nil),  // 18: openctl.v1.ListOperationsRequest
	(*ListOperationsResponse)(nil), // 19: openctl.v1.ListOperationsResponse
	(*LoginRequest)(nil),           // 20: openctl.v1.LoginRequest
	(*LoginResponse)(nil),          // 21: openctl.v1.LoginResponse
	(*LogoutRequest)(nil),          // 22: openctl.v1.LogoutRequest
	(*LogoutResponse)(nil),         // 23: openctl.v1.LogoutResponse
	(*WhoAmIRequest)(nil),          // 24: openctl.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),         // 25: openctl.v1.WhoAmIResponse
	(*ListSchemasRequest)(nil),     // 26: openctl.v1.ListSchemasRequest
	(*ListSchemasResponse)(nil),    // 27: openctl.v1.ListSchemasResponse
	(*SchemaInfo)(nil),             // 28: openctl.v1.SchemaInfo
	(*GetSchemaRequest)(nil),       // 29: openctl.v1.GetSchemaRequest
	(*GetSchemaResponse)(nil),      // 30: openctl.v1.GetSchemaResponse
	(*ValidateRequest)(nil),        // 31: openctl.v1.ValidateRequest
	(*ValidateResponse)(nil),       // 32: openctl.v1.ValidateResponse
	(*WatchOperationsRequest)(nil), // 33: openctl.v1.WatchOperationsRequest
	(*OperationEvent)(nil),         // 34: openctl.v1.OperationEvent
	nil,                            // 35: openctl.v1.Metadata.LabelsEntry
	nil,                            // 36: openctl.v1.Metadata.AnnotationsEntry
	(*structpb.Struct)(nil),        // 37: google.protobuf.Struct
}
var file_api_proto_depIdxs = []int32{
	5,  // 0: openctl.v1.Resource.metadata:type_name -> openctl.v1.Metadata
	37, // 1: openctl.v1.Resource.spec:type_name -> google.protobuf.Struct
	37, // 2: openctl.v1.Resource.status:type_name -> google.protobuf.Struct
	4,  // 3: openctl.v1.Resource.drift:type_name -> openctl.v1.DriftEntry
	35, // 4: openctl.v1.Metadata.labels:type_name -> openctl.v1.Metadata.LabelsEntry
	36, // 5: openctl.v1.Metadata.annotations:type_name -> openctl.v1.Metadata.AnnotationsEntry
	3,  // 6: openctl.v1.ApplyRequest.resource:type_name -> openctl.v1.Resource
	3,  // 7: openctl.v1.GetResponse.resource:type_name -> openctl.v1.Resource
	3,  // 8: openctl.v1.ListResponse.resources:type_name -> openctl.v1.Resource
	0,  // 9: openctl.v1.WatchEvent.type:type_name -> openctl.v1.WatchEvent.Type
	3,  // 10: openctl.v1.WatchEvent.resource:type_name -> openctl.v1.Resource
	3,  // 11: openctl.v1.Operation.result:type_name -> openctl.v1.Resource
	16, // 12: openctl.v1.Operation.children:type_name -> openctl.v1.Operation
	16, // 13: openctl.v1.ListOperationsResponse.operations:type_name -> openctl.v1.Operation
	28, // 14: openctl.v1.ListSchemasResponse.schemas:type_name -> openctl.v1.SchemaInfo
	28, // 15: openctl.v1.GetSchemaResponse.info:type_name -> openctl.v1.SchemaInfo
	3,  // 16: openctl.v1.ValidateRequest.resource:type_name -> openctl.v1.Resource
	16, // 17: openctl.v1.OperationEvent.operation:type_name -> openctl.v1.Operation
	1,  // 18: openctl.v1.PingService.Ping:input_type -> openctl.v1.PingRequest
	6,  // 19: openctl.v1.ResourceService.Apply:input_type -> openctl.v1.ApplyRequest
	8,  // 20: openctl.v1.ResourceService.Get:input_type -> openctl.v1.GetRequest
	10, // 21: openctl.v1.ResourceService.List:input_type -> openctl.v1.ListRequest
	12, // 22: openctl.v1.ResourceService.Delete:input_type -> openctl.v1.DeleteRequest
	14, // 23: openctl.v1.ResourceService.Watch:input_type -> openctl.v1.WatchRequest
	17, // 24: openctl.v1.OperationService.GetOperation:input_type -> openctl.v1.GetOperationRequest
	18, // 25: openctl.v1.OperationService.ListOperations:input_type -> openctl.v1.ListOperationsRequest
	33, // 26: openctl.v1.OperationService.WatchOperations:input_type -> openctl.v1.WatchOperationsRequest
	20, // 27: openctl.v1.SessionService.Login:input_type -> openctl.v1.LoginRequest
	22, // 28: openctl.v1.SessionService.Logout:input_type -> openctl.v1.LogoutRequest
	24, // 29: openctl.v1.SessionService.WhoAmI:input_type -> openctl.v1.WhoAmIRequest
	26, // 30: openctl.v1.SchemaService.ListSchemas:input_type -> openctl.v1.ListSchemasRequest
	29, // 31: openctl.v1.SchemaService.GetSchema:input_type -> openctl.v1.GetSchemaRequest
	31, // 32: openctl.v1.SchemaService.Validate:input_type -> openctl.v1.ValidateRequest
	2,  // 33: openctl.v1.PingService.Ping:output_type -> openctl.v1.PingResponse
	7,  // 34: openctl.v1.ResourceService.Apply:output_type -> openctl.v1.ApplyResponse
	9,  // 35: openctl.v1.ResourceService.Get:output_type -> openctl.v1.GetResponse
	11, // 36: openctl.v1.ResourceService.List:output_type -> openctl.v1.ListResponse
	13, // 37: openctl.v1.ResourceService.Delete:output_type -> openctl.v1.DeleteResponse
	15, // 38: openctl.v1.ResourceService.Watch:output_type -> openctl.v1.WatchEvent
	16, // 39: openctl.v1.OperationService.GetOperation:output_type -> openctl.v1.Operation
	19, // 40: openctl.v1.OperationService.ListOperations:output_type -> openctl.v1.ListOperationsResponse
	34, // 41: openctl.v1.OperationService.WatchOperations:output_type -> openctl.v1.OperationEvent
	21, // 42: openctl.v1.SessionService.Login:output_type -> openctl.v1.LoginResponse
	23, // 43: openctl.v1.SessionService.Logout:output_type -> openctl.v1.LogoutResponse
	25, // 44: openctl.v1.SessionService.WhoAmI:output_type -> openctl.v1.WhoAmIResponse
	27, // 45: openctl.v1.SchemaService.ListSchemas:output_type -> openctl.v1.ListSchemasResponse
	30, // 46: openctl.v1.SchemaService.GetSchema:output_type -> openctl.v1.GetSchemaResponse
	32, // 47: openctl.v1.SchemaService.Validate:output_type -> openctl.v1.ValidateResponse
	33, // [33:48] is the sub-list for method output_type
	18, // [18:33] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
